version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=expense-tracker
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
